print('Team Member Details')
a=input('Firstname?')
print('First Name: %s'%(a))
b=input('what is your Last name')
print('Last name: %s'%(b))
c=input('which company are you working?')
print('Company Name: %s'%(c))
d=input('What is your work location')
print('WorK Location: %s'%(d))

'''
print('Team Member Details')
a=input('Firstname?')
print('First Name')
print(a)
b=input('what is your Last name')
print('Last name')
print(b)
c=input('where do you work?')
print('Company')
print(c)
d=input('What is your work location')
print('WorK Location')
print(d)
'''
